// src/app/robots.txt/route.ts
// Robots.txt per site domain

import { headers } from 'next/headers';

// R1.2: Revalidate once per day
export const revalidate = 86400;

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3201';

export async function GET() {
  // R1.1: await headers()
  const headersList = await headers();
  const host = headersList.get('host') ?? '';
  const forwardedHost = headersList.get('x-forwarded-host') ?? '';
  const domain = forwardedHost || host;

  // Build canonical base URL for this domain
  const protocol = domain.includes('localhost') ? 'http' : 'https';
  const baseUrl = domain
    ? `${protocol}://${domain}`
    : SITE_URL;

  const robotsTxt = `# Robots.txt for ${domain || 'News Platform'}
# Generated by Next.js Multi-Site Platform

User-agent: *
Allow: /

# Disallow admin and API routes
Disallow: /api/
Disallow: /_next/
Disallow: /admin/

# Crawl-delay (optional, for polite crawlers)
Crawl-delay: 1

# Sitemap
Sitemap: ${baseUrl}/sitemap.xml

# RSS Feed
# ${baseUrl}/rss.xml
`;

  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=604800',
    },
  });
}
